name: Android Tests CI

on:
  workflow_dispatch:
  push:
    branches: [ javac-17 ]
  pull_request:
    branches: [ javac-17 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: set up JDK 11
      uses: actions/setup-java@main
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test
